name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: centos:8
    steps:
      - uses: actions/checkout@v2
      - name: "Install build dependencies"
        run: dnf install -y python2 python2-pip rpm-build rsync
      - name: Install python dependencies
        run: pip2 install SQLObject
      - name: "Create rpm"
        run: ./build-togo.sh
      - name: "Test and install the rpm"
        run: dnf install -y rpms/*.rpm
      - name: "Create release"
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
